# Association Rule Mining

- Measure of Association
- - Support
  - Confidence
  - Lift.

## Association rule mining: Given a set of transactions T, the goal of association rule minig is to find all rules having 
- support >= minsup threshold
- confidence >= minconf threshold.

## Steps for Apriori Algorithm.
- Step 1: Determine the support of items sets in the transactional database, and selec the minimum support and confidence.
- Step 2: Take all supports in the transaction with higher support value than the minimum or selected support value.
- Step 3: Find all the rules of these subsets that have higher confidence value than the threshold or minimum confidence.
- Step 4: Sort the rules as the decreasing order of lift.

In [1]:
data = [["milk", "bread", "rice", "book"],
        ["bread","jam","book","pen"],
        ["jam","milk","bread","rice","eggs"],
        ["rice","eggs","pen","book"],
        ["eggs","pen","milk","bread","jam"],
        ["eggs","rice","bread","jam"]]

In [5]:
pip install mlxtend

Collecting mlxtend
  Downloading mlxtend-0.23.1-py3-none-any.whl (1.4 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.4/1.4 MB 13.5 MB/s eta 0:00:00 MB/s eta 0:00:0101
Requirement already satisfied: scipy>=1.2.1 in /Users/puli/opt/anaconda3/lib/python3.9/site-packages (from mlxtend) (1.7.3)
Requirement already satisfied: scikit-learn>=1.0.2 in /Users/puli/opt/anaconda3/lib/python3.9/site-packages (from mlxtend) (1.0.2)
Requirement already satisfied: pandas>=0.24.2 in /Users/puli/opt/anaconda3/lib/python3.9/site-packages (from mlxtend) (1.4.4)
Requirement already satisfied: matplotlib>=3.0.0 in /Users/puli/opt/anaconda3/lib/python3.9/site-packages (from mlxtend) (3.6.2)
Requirement already satisfied: numpy>=1.16.2 in /Users/puli/opt/anaconda3/lib/python3.9/site-packages (from mlxtend) (1.21.5)
Requirement already satisfied: joblib>=0.13.2 in /Users/puli/opt/anaconda3/lib/python3.9/site-packages (from mlxtend) (1.1.1)
Requirement already satisfied: packaging>=20.0 in /Users/puli/opt/anaconda3/lib/python3.9/site-packages (from matplotlib>=3.0.0->mlxtend) (22.0)
Requirement already satisfied: pyparsing>=2.2.1 in /Users/puli/opt/anaconda3/lib/python3.9/site-packages (from matplotlib>=3.0.0->mlxtend) (3.0.9)
Requirement already satisfied: fonttools>=4.22.0 in /Users/puli/opt/anaconda3/lib/python3.9/site-packages (from matplotlib>=3.0.0->mlxtend) (4.25.0)
Requirement already satisfied: contourpy>=1.0.1 in /Users/puli/opt/anaconda3/lib/python3.9/site-packages (from matplotlib>=3.0.0->mlxtend) (1.0.5)
Requirement already satisfied: cycler>=0.10 in /Users/puli/opt/anaconda3/lib/python3.9/site-packages (from matplotlib>=3.0.0->mlxtend) (0.11.0)
Requirement already satisfied: pillow>=6.2.0 in /Users/puli/opt/anaconda3/lib/python3.9/site-packages (from matplotlib>=3.0.0->mlxtend) (9.3.0)
Requirement already satisfied: python-dateutil>=2.7 in /Users/puli/opt/anaconda3/lib/python3.9/site-packages (from matplotlib>=3.0.0->mlxtend) (2.8.2)
Requirement already satisfied: kiwisolver>=1.0.1 in /Users/puli/opt/anaconda3/lib/python3.9/site-packages (from matplotlib>=3.0.0->mlxtend) (1.4.4)
Requirement already satisfied: pytz>=2020.1 in /Users/puli/opt/anaconda3/lib/python3.9/site-packages (from pandas>=0.24.2->mlxtend) (2022.7)
Requirement already satisfied: threadpoolctl>=2.0.0 in /Users/puli/opt/anaconda3/lib/python3.9/site-packages (from scikit-learn>=1.0.2->mlxtend) (2.2.0)
Requirement already satisfied: six>=1.5 in /Users/puli/opt/anaconda3/lib/python3.9/site-packages (from python-dateutil>=2.7->matplotlib>=3.0.0->mlxtend) (1.16.0)
Installing collected packages: mlxtend
Successfully installed mlxtend-0.23.1
Note: you may need to restart the kernel to use updated packages.

In [2]:
from mlxtend.preprocessing import TransactionEncoder
te = TransactionEncoder()
te_array = te.fit_transform(data)

In [4]:
import pandas as pd

In [6]:
df = pd.DataFrame(te_array,columns=te.columns_)
df

    book  bread   eggs    jam   milk    pen   rice
0   True   True  False  False   True  False   True
1   True   True  False   True  False   True  False
2  False   True   True   True   True  False   True
3   True  False   True  False  False   True   True
4  False   True   True   True   True   True  False
5  False   True   True   True  False  False   True

In [19]:
#import the libray to get support. 
from mlxtend.frequent_patterns import apriori
itemset = apriori(df,min_support=0.5,use_colnames=True)
itemset

     support            itemsets
0   0.500000              (book)
1   0.833333             (bread)
2   0.666667              (eggs)
3   0.666667               (jam)
4   0.500000              (milk)
5   0.500000               (pen)
6   0.666667              (rice)
7   0.500000       (bread, eggs)
8   0.666667        (bread, jam)
9   0.500000       (bread, milk)
10  0.500000       (bread, rice)
11  0.500000         (jam, eggs)
12  0.500000        (eggs, rice)
13  0.500000  (bread, jam, eggs)

In [20]:
from mlxtend.frequent_patterns import association_rules
res = association_rules(itemset,metric="confidence",min_threshold=0.5)
res

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction,zhangs_metric
0,(bread),(eggs),0.833333,0.666667,0.500000,0.60,0.900,-0.055556,0.833333,-0.400000
1,(eggs),(bread),0.666667,0.833333,0.500000,0.75,0.900,-0.055556,0.666667,-0.250000
2,(bread),(jam),0.833333,0.666667,0.666667,0.80,1.200,0.111111,1.666667,1.000000
3,(jam),(bread),0.666667,0.833333,0.666667,1.00,1.200,0.111111,inf,0.500000
4,(bread),(milk),0.833333,0.500000,0.500000,0.60,1.200,0.083333,1.250000,1.000000
5,(milk),(bread),0.500000,0.833333,0.500000,1.00,1.200,0.083333,inf,0.333333
6,(bread),(rice),0.833333,0.666667,0.500000,0.60,0.900,-0.055556,0.833333,-0.400000
7,(rice),(bread),0.666667,0.833333,0.500000,0.75,0.900,-0.055556,0.666667,-0.250000
8,(jam),(eggs),0.666667,0.666667,0.500000,0.75,1.125,0.055556,1.333333,0.333333
9,(eggs),(jam),0.666667,0.666667,0.500000,0.75,1.125,0.055556,1.333333,0.333333
10,(eggs),(rice),0.666667,0.666667,0.500000,0.75,1.125,0.055556,1.333333,0.333333
11,(rice),(eggs),0.666667,0.666667,0.500000,0.75,1.125,0.055556,1.333333,0.333333
12,"(bread, jam)",(eggs),0.666667,0.666667,0.500000,0.75,1.125,0.055556,1.333333,0.333333
13,"(bread, eggs)",(jam),0.500000,0.666667,0.500000,1.00,1.500,0.166667,inf,0.666667
14,"(jam, eggs)",(bread),0.500000,0.833333,0.500000,1.00,1.200,0.083333,inf,0.333333
15,(bread),"(jam, eggs)",0.833333,0.500000,0.500000,0.60,1.200,0.083333,1.250000,1.000000
16,(jam),"(bread, eggs)",0.666667,0.500000,0.500000,0.75,1.500,0.166667,2.000000,1.000000
17,(eggs),"(bread, jam)",0.666667,0.666667,0.500000,0.75,1.125,0.055556,1.333333,0.333333

In [21]:
result = res[["antecedents", "consequents","support","confidence","lift"]]
result

      antecedents    consequents   support  confidence   lift
0         (bread)         (eggs)  0.500000        0.60  0.900
1          (eggs)        (bread)  0.500000        0.75  0.900
2         (bread)          (jam)  0.666667        0.80  1.200
3           (jam)        (bread)  0.666667        1.00  1.200
4         (bread)         (milk)  0.500000        0.60  1.200
5          (milk)        (bread)  0.500000        1.00  1.200
6         (bread)         (rice)  0.500000        0.60  0.900
7          (rice)        (bread)  0.500000        0.75  0.900
8           (jam)         (eggs)  0.500000        0.75  1.125
9          (eggs)          (jam)  0.500000        0.75  1.125
10         (eggs)         (rice)  0.500000        0.75  1.125
11         (rice)         (eggs)  0.500000        0.75  1.125
12   (bread, jam)         (eggs)  0.500000        0.75  1.125
13  (bread, eggs)          (jam)  0.500000        1.00  1.500
14    (jam, eggs)        (bread)  0.500000        1.00  1.200
15        (bread)    (jam, eggs)  0.500000        0.60  1.200
16          (jam)  (bread, eggs)  0.500000        0.75  1.500
17         (eggs)   (bread, jam)  0.500000        0.75  1.125

In [23]:
result[result["support"]>=0.5]

      antecedents    consequents   support  confidence   lift
0         (bread)         (eggs)  0.500000        0.60  0.900
1          (eggs)        (bread)  0.500000        0.75  0.900
2         (bread)          (jam)  0.666667        0.80  1.200
3           (jam)        (bread)  0.666667        1.00  1.200
4         (bread)         (milk)  0.500000        0.60  1.200
5          (milk)        (bread)  0.500000        1.00  1.200
6         (bread)         (rice)  0.500000        0.60  0.900
7          (rice)        (bread)  0.500000        0.75  0.900
8           (jam)         (eggs)  0.500000        0.75  1.125
9          (eggs)          (jam)  0.500000        0.75  1.125
10         (eggs)         (rice)  0.500000        0.75  1.125
11         (rice)         (eggs)  0.500000        0.75  1.125
12   (bread, jam)         (eggs)  0.500000        0.75  1.125
13  (bread, eggs)          (jam)  0.500000        1.00  1.500
14    (jam, eggs)        (bread)  0.500000        1.00  1.200
15        (bread)    (jam, eggs)  0.500000        0.60  1.200
16          (jam)  (bread, eggs)  0.500000        0.75  1.500
17         (eggs)   (bread, jam)  0.500000        0.75  1.125